name: scadnano
description: A web-based scriptable cadnano (see https://cadnano.org/ for original cadnano developed by Shawn Douglas).
# version: 0.0.1
#homepage: https://web.cs.ucdavis.edu/~doty/scadnano/
#author: David Doty <doty@ucdavis.edu>

environment:
  sdk: ^2.6.0

dependencies:
  js: ^0.6.1+1
  codemirror: ^0.5.11
  color: ^2.1.1
  tuple: ^1.0.2
  quiver: ^2.0.5
  test: ^1.5.1+1
  meta: ^1.1.7
  path: ^1.6.4
  platform_detect: ^1.3.5
  dnd: ^1.4.2
  redux: ^3.0.0
#  built_value: ^7.0.0
  built_value: ^6.8.2
  react: ^5.1.0
#  over_react: ^3.1.0

dependency_overrides:
#  react:
#    git:
#      url: https://github.com/cleandart/react-dart
#      ref: 5.1.0-wip
  over_react:
    git:
      url: https://github.com/Workiva/over_react
      ref: master
#      ref: 4d6bab5b30c3354d34260ef0c9250209f5da3764

dev_dependencies:
#  built_value_generator: ^7.0.0
  built_value_generator: ^6.7.1
  build_runner: ^1.6.2
  build_web_compilers: ^2.3.0
  redux_dev_tools: ^0.4.0
